### ISSUE TITLE
TypeError: intersectsObjFromSpider is undefined

### ISSUE THREAD

**Issue by weiserhei** [lorenzomighie/Videogame-in-threee.js#2]
First of all: great game, its truly original and i like the freedom to solve eache riddle individually!
However, I did it 4 times because i closed the tab 2 times while casting a net and walking (strg+w) - please prevent this shortcut and display a warning 😃 

The third time the game crashed on me when i walked the roof and tried to cast a Net with:
```
TypeError: intersectsObjFromSpider is undefined Game.js:879
```
https://github.com/lorenzomighie/Videogame-in-threee.js/blob/master/src/game/Game.js#L879

**Comment by lorenzomighie** [comment]
Sorry about the first issue, unfortunately that is a problem of using ctrl in the browser.

The second error is pretty weird, it seem that the raycaster does not intersect any objects, thank you for pointing it out !
